---
output: 
  officedown::rdocx_document:
    # number_sections: false
    # reference_docx: template.docx
    tables:
      # style: stat_table
      caption:
        # style: TableCaption
        pre: "Table "
        sep: ": "
    plots:
      align: center
    page_size:
      width: 8.5
      heigh: 11
    page_margins:
      bottom: 1
      top: 1
      right: 1
      left: 1
      gutter: 0
# header-includes:
#   \usepackage{booktabs}
#   \usepackage{dcolumn}  
---

```{r setup, include = FALSE}
l <- readRDS("data/lagrange.Rds")
library(tidyverse)
library(spatialreg)
library(officedown)
source("R/extract.R")
model_list <- readr::read_rds("model_list.Rds")
```

```{r echo = FALSE, fig.cap = "Lagrange Multiplier", fig.id = "lagrange"}
l$p.value <- as.character(signif(l$p.value))
l
```

RENAME RHO IN MODEL
```{r echo = FALSE, eval=F}
# extract_list <-
#   purrr::map(
#     model_list,
#     function(x){
#       e <- texreg::extract(x)
#       e@coef.names[length(e@coef.names)] <- "rho"
#       return(e)
#     }
#   )
model_list %>% 
  map(
    function(x){
      extract.Sarlm2(x)
    }
  ) %>% 
texreg::knitreg(
  # file = "texreg.docx",
  single.row = T,
  booktabs = T,
  dcolumn = T, custom.model.names = c("MHLTH", "DEPRESSION", "SLEEP"),
  custom.coef.names = c(
NA,

"Mean NDVI",
"Greenspace Area",
"Percent White",
"Income",
"Amenities",
"Trails",
"rho"

  ),
float.pos = "h"
)

```





<!-- \begin{table} -->
<!-- \begin{center} -->
<!-- \begin{tabular}{l D{)}{)}{9)3} D{)}{)}{9)3} D{)}{)}{9)3}} -->
<!-- \toprule -->
<!--  & \multicolumn{1}{c}{MHLTH} & \multicolumn{1}{c}{DEPRESSION} & \multicolumn{1}{c}{SLEEP} \\ -->
<!-- \midrule -->
<!-- (Intercept)         & 10.15 \; (1.73)^{***} & 9.58 \; (2.12)^{***} & 14.45 \; (2.19)^{***} \\ -->
<!-- $\rho$              & 0.59 \; (0.08)^{***}  & 0.62 \; (0.08)^{***} & 0.78 \; (0.05)^{***}  \\ -->
<!-- Mean NDVI           & 0.87 \; (2.53)        & 1.69 \; (2.21)       & -1.38 \; (2.60)       \\ -->
<!-- Greenspace Area     & 0.29 \; (0.32)        & 0.21 \; (0.28)       & 0.74 \; (0.33)^{*}    \\ -->
<!-- Percent White       & -4.48 \; (1.11)^{***} & -0.57 \; (0.97)      & -6.98 \; (1.15)^{***} \\ -->
<!-- Income              & -4.64 \; (1.16)^{***} & -2.92 \; (1.01)^{**} & -5.71 \; (1.19)^{***} \\ -->
<!-- Amenities           & -0.00 \; (0.01)       & -0.00 \; (0.01)      & -0.02 \; (0.01)^{*}   \\ -->
<!-- Trails              & -0.18 \; (0.56)       & -0.26 \; (0.49)      & -0.28 \; (0.58)       \\ -->
<!-- \midrule -->
<!-- Num. obs.           & 151                   & 151                  & 151                   \\ -->
<!-- Parameters          & 9                     & 9                    & 9                     \\ -->
<!-- Log Likelihood      & -263.91               & -244.48              & -274.50               \\ -->
<!-- AIC (Linear model)  & 584.95                & 550.63               & 670.83                \\ -->
<!-- AIC (Spatial model) & 545.82                & 506.96               & 567.00                \\ -->
<!-- LR test: statistic  & 41.13                 & 45.67                & 105.82                \\ -->
<!-- LR test: p-value    & 0.00                  & 0.00                 & 0.00                  \\ -->
<!-- \bottomrule -->
<!-- \multicolumn{4}{l}{\scriptsize{$^{***}p<0.001$; $^{**}p<0.01$; $^{*}p<0.05$}} -->
<!-- \end{tabular} -->
<!-- \caption{Statistical models} -->
<!-- \label{table:coefficients} -->
<!-- \end{center} -->
<!-- \end{table} -->

